Fix return type deprecations
lightSAML/lightSAML pull request #156
Opened 2022-03-21 20:07 UTC by nztim

This is intended to fix some return type deprecation notices on PHP 8.1.

2022-03-23 16:34 UTC, william-suppo requested changes
Hello @nztim, thank you for your PR.

I review your code and add some comments.

Bye.

2022-03-23 16:34 UTC, william-suppo commented on src/LightSaml/Context/AbstractContext.php
> +    public function getIterator(): \Traversable
ArrayIterator does not implémente Traversable (https://www.php.net/manual/fr/class.arrayiterator.php)
Can you use the good type and remove the phpdoc ?

2022-03-23 16:34 UTC, william-suppo commented on src/LightSaml/Meta/ParameterBag.php
> +    public function getIterator(): \Traversable
ArrayIterator does not implémente Traversable (https://www.php.net/manual/fr/class.arrayiterator.php)
Can you use the good type and remove the phpdoc ?

2022-03-23 16:34 UTC, william-suppo commented on src/LightSaml/Meta/ParameterBag.php
> +    public function count(): int
can you remove the phpdoc ?

2022-03-23 19:09 UTC, nztim commented
Yes I should have used the actual return types rather than those from the interface. How about this?

2022-03-24 12:23 UTC, merged

2022-03-24 12:27 UTC, william-suppo commented
Thx for your PR, 2.3.3 was tagged.

Bye